### ISSUE TITLE
Failsafe and ignore file after amount of time 

### ISSUE THREAD

**Issue by frbuccoliero** [C0D3D3V/Moodle-Downloader-2#109]
Hi there, thanks for your awesome project. Everything fine also with SSO auth , but i have a small problem. In one of my courses (don't actually know which one) there is a link to a microsoft teams Meeting, the script tries to download file from it and it gets stuck.
Is there any chance of skipping it and/or enabling a failsafe algorythm to stop trying and ignoring certain links failing to download?

![Download stuck](https://user-images.githubusercontent.com/14348908/134952107-7e26083e-0f6c-4eb6-869f-fb2a6c0290bb.png)

Thanks a lot.

**Comment by C0D3D3V** [comment]
try `moodle-dl --without-downloading-files` this will run the downloader without downloading any file, but adding all files that would be downloaded to the lokal database.

**Comment by frbuccoliero** [comment]
Ok, it worked. Nice walkaround!
Btw as a suggestion would be cool to add a blacklist to prevent certain things from being downloaded. 
Thanks again!

**Comment by C0D3D3V** [comment]
The only blacklist we currently have is a domain-based blacklist. Take a look at it: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Download-(external)-linked-files#whitelist-and-blacklist

If you need more, make a suggestion or just make a pull request :)
