### ISSUE TITLE
[Feature request] Exclude Moodle videos

### ISSUE THREAD

**Issue by gilleswaeber** [C0D3D3V/Moodle-Downloader-2#110]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

Some courses I'm subscribed to contain videos (e.g. course recordings) as Moodle files (they are not external links) and there's no way to tell moodle-dl not to download them.

## Describe the solution you'd like

I'd like a way to exclude some files using file extensions.

## Describe alternatives you've considered

Domain whitelists don't work since the videos are hosted on Moodle.

## Additional context

Thank you for your tool, it's very useful.

**Comment by C0D3D3V** [comment]
Excluding Moodle files by file extension or MIME type should not be a big problem.
It is difficult with all external links that are downloaded via youtube-dl, there we can not filter by extensions as it is currently implemented. But you are only interested in the files on moodle. I'll have a look at it in the next few days and think about something.

**Comment by gilleswaeber** [comment]
Sorry for the delay, I just tested it and it works exactly as expected.

Thank you!
