### ISSUE TITLE
Automate getting SSO token by using a custom URL-Scheme Handler

### ISSUE THREAD

**Issue by C0D3D3V** [C0D3D3V/Moodle-Downloader-2#112]
We only need to define ~~`moodle-dl`~~ `moodlemobile` as URI on all common systems during installation. And then catch the token in another instance :)

This is how it works on linux: https://archive.is/8C3zb
Here for all other operation systems: https://css-tricks.com/hyperlinking-beyond-the-web/

**Comment by C0D3D3V** [comment]
In the newer Moodle versions, the [default urlscheme is always forced](https://git.in.moodle.com/moodle/moodle/-/blob/master/admin/tool/mobile/launch.php#L101) by default, which is `moodlemobile`.

So it is not enough to register `moodl-dl`, we have to register the dektop app `moodlemobile`.


The .desktop file could look like this:
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=moodle-dl %U
Name[en_US]=Moodle-DL
Name=Moodle-DL
Categories=Application;Network;
MimeType=x-scheme-handler/moodlemobile;
Comment=A Moodle downloader that downloads course content fast from Moodle (eg. lecture pdfs)
Comment[en_US]=A Moodle downloader that downloads course content fast from Moodle (eg. lecture pdfs) 
Comment[en_US.utf8]=A Moodle downloader that downloads course content fast from Moodle (eg. lecture pdfs) 
```

**Comment by septatrix** [comment]
I remembered that there we some other issues with the callback url when I tried it so here are my thoughts:

1. It is not RFC compliant meaning that we have to manually parse it (which should however be trivial). [moodlemobile scheme is not RFC compliant](https://tracker.moodle.org/browse/MDL-72829?filter=-2&jql=resolution%20%3D%20Unresolved%20AND%20reporter%20in%20(currentUser())%20order%20by%20created%20DESC)
2. We could also try to get implement a reasonable callback support upstream. Apparently I already made a corresponding issue a year ago ([Allow custom callback url for admin/tool/mobile/launch.php](https://tracker.moodle.org/browse/MDL-70428?filter=-2&jql=resolution%20%3D%20Unresolved%20AND%20reporter%20in%20(currentUser())%20order%20by%20created%20DESC)) though that will obviously take some time and not be supported everywhere directly.
3. I just stumbled upon this: We could register a protocol handler in the browser using `navigator.registerProtocolHandler("web+moodlemobile", "https://example.com/?q=%s", "moodle-dl")` which is supported in Chromium browsers and Firefox. The function would have to be called from the same origin as to which it would redirect though I assume it is simply possible to replace `example.com` with `localhost:8080` (no longer a privileged port, yay!) and send the user to that page before redirecting them to their moodle login. Sadly the `web+` prefix is required though I do not think that the `forcedurlscheme` is configured by default.

Having just found out about the third option I think it is probably the cleanest solution. For unsupported platforms e.g. MacOS users without one of the above browsers we could still offer the current solution of manually copying the token as I do not think it is worth the hassle to get scheme handlers working cross platform manually. This would also synergize pretty well with a potential web-server based ui. The final goal might still be upstream support for use-cases like ours but that is not in the near future and even once implemented would have to trickle down to most hosted instances.

**Comment by C0D3D3V** [comment]
Just a quick reply... forcedurlscheme is set default
. I don't feel like looking up the source code right now but if you set up a fresh moodle instance you will see that it is enabled.

the moodle desktop app registers the url handler on both windows and linux and it works. so i think this should not be a problem. it's just a question of when someone or I will have time to implement it.

**Comment by Megver83** [comment]
BTW, remember that [Moodle Desktop has been discontinued](https://moodle.org/mod/forum/discuss.php?d=413350), so I think you should update the wiki and notify users that this method might stop working at some time and look for another "always working method"

**Comment by C0D3D3V** [comment]
An more simpler and more general way would be to use a WebView and let the user login inside that WebView...
