### ISSUE TITLE
Pass the original url to external file downloaders

### ISSUE THREAD

**Issue by jnnkB** [C0D3D3V/Moodle-Downloader-2#127]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

I use currently the `external_file_downloaders` config option to download files from my universities servers. Unfortunately they only get  the  redirected URL. But since this is only the URL of our SSO, my script can't download the file.

## Describe the solution you'd like

Pass the original URL instead of the URL after the redirect.

The problem is in the following line:
https://github.com/C0D3D3V/Moodle-Downloader-2/blob/32eba23cc1bddaf84d02144658a62c3e9b4f777c/moodle_dl/download_service/url_target.py#L447

**Comment by C0D3D3V** [comment]
Should be fixed with 1cd04ec , you are welcome to test it.
