### ISSUE TITLE
Download embedded YouTube videos

### ISSUE THREAD

**Issue by AlexBocken** [C0D3D3V/Moodle-Downloader-2#128]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

I've noticed how a few of my courses embed youtube videos in their course material. It's not a direct link per se. These videos do not get downloaded by moodle-dl.

## Describe the solution you'd like

Find these embedded youtube videos and download them as you would with youtube links.

## Additional context

You can see the html of such a case attached if it's of any help for you. 

A particular line that includes such a video would be:
```html
<div role="main"><span id="maincontent"></span><h2>Week 8. Lean II</h2><div id="intro" class="box py-3 generalbox"><div class="no-overflow"><p dir="ltr" style="text-align: left;"><strong>21. Company-specific production systems</strong><br></p><p dir="ltr" style="text-align: left;"><span><strong><div class="mediaplugin mediaplugin_videojs d-block"><div style="max-width:400px;"><video data-setup-lazy="{&quot;techOrder&quot;: [&quot;youtube&quot;], &quot;sources&quot;: [{&quot;type&quot;: &quot;video/youtube&quot;, &quot;src&quot;:&quot;https://youtu.be/3R92_xHULBQ&quot;}], &quot;language&quot;: &quot;en&quot;, &quot;fluid&quot;: true}" id="id_videojs_6193edac5ac33_1" class="video-js" preload="auto" controls="true" title="21. Company-specific production systems"><a class="mediafallbacklink" href="https://youtu.be/3R92_xHULBQ">21. Company-specific production systems</a></video></div></div></strong></span></p><p dir="ltr" style="text-align: left;"><span><strong><br></strong></span></p><p dir="ltr" style="text-align: left;"><span><span><strong>22. Problem solving methods</strong></span></span></p><p dir="ltr" style="text-align: left;"><span><span><span><span style=""><strong><div class="mediaplugin mediaplugin_videojs d-block"><div style="max-width:400px;"><video data-setup-lazy="{&quot;techOrder&quot;: [&quot;youtube&quot;], &quot;sources&quot;: [{&quot;type&quot;: &quot;video/youtube&quot;, &quot;src&quot;:&quot;https://youtu.be/de1bhn993og&quot;}], &quot;language&quot;: &quot;en&quot;, &quot;fluid&quot;: true}" id="id_videojs_6193edac5acc6_2" class="video-js" preload="auto" controls="true" title="22. Problem solving methods"><a class="mediafallbacklink" href="https://youtu.be/de1bhn993og">22. Problem solving methods</a></video></div></div></strong></span><br></span></span></span></p></div></div><div class="box generalbox pt-0 pb-3 foldertree"><div id="folder_tree0" class="filemanager"><ul><li><div class="fp-filename-icon"><span class="fp-icon"><img class="icon " alt="" aria-hidden="true" src="https://moodle-app2.let.ethz.ch/theme/image.php/boost_ethz/core/1636613796/f/folder-24" /></span><span class="fp-filename"></span></div><ul><li><span class="fp-filename-icon"><a href="https://moodle-app2.let.ethz.ch/pluginfile.php/1205781/mod_folder/content/0/L8_Lean%20II_key%20slides.pdf?forcedownload=1"><span class="fp-icon"><img class="icon " alt="L8_Lean II_key slides.pdf" title="L8_Lean II_key slides.pdf" src="https://moodle-app2.let.ethz.ch/theme/image.php/boost_ethz/core/1636613796/f/pdf-24" /></span><span class="fp-filename">L8_Lean II_key slides.pdf</span></a></span></li><li><span class="fp-filename-icon"><a href="https://moodle-app2.let.ethz.ch/pluginfile.php/1205781/mod_folder/content/0/XPS%20deep%20dive.pdf?forcedownload=1"><span class="fp-icon"><img class="icon " alt="XPS deep dive.pdf" title="XPS deep dive.pdf" src="https://moodle-app2.let.ethz.ch/theme/image.php/boost_ethz/core/1636613796/f/pdf-24" /></span><span class="fp-filename">XPS deep dive.pdf</span></a></span></li></ul></li></ul></div></div><div class="box generalbox pt-0 pb-3 folderbuttons"><div class="singlebutton">
```
Here's the full html. I hope theres nothing too confidential in there.
[embedded_yt.html.txt](https://github.com/C0D3D3V/Moodle-Downloader-2/files/7548715/embedded_yt.html.txt)

**Comment by C0D3D3V** [comment]
You are using the master branch right?

this is a /mod/page website correct? We switched downloading /mod/page from markdown files to html files. I forgot that, then no likes are crawled in that file. We have two options, we switch back to downloading /mod/page as markdown or we also crawl the links in the html file.

**Comment by C0D3D3V** [comment]
I think crawling links in the html version would be the better way. I had decided to dowbload pages as html, because some pages have quite complicated representations.


However, I would be interested in the responses.log file that you can generate via `moodle-dl --log-responses`. You are welcome to send it to me by mail. 
I see that there are links to two folders in the page, I would be interested if they also come back from the API as linked files, because then we should not crawl them in the page html.

**Comment by AlexBocken** [comment]
> You are using the master branch right?

Yes, I'm just using the AUR package.

>this is a /mod/page website correct?

Yes, the url ends with `/mod/folder/view.php?id=<id>`

> However, I would be interested in the responses.log file that you can generate via moodle-dl --log-responses. You are welcome to send it to me by mail.

Check your Inbox.

**Comment by C0D3D3V** [comment]
I ask to test the latest change be1e267, I will publish that in the next release.

**Comment by AlexBocken** [comment]
Thanks so much for your quick work! I tested it and couldn't find any problems from my side. Everything works as expected.
