### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by fulcus** [C0D3D3V/Moodle-Downloader-2#129]
Can you provide a quick guide on how to install from source? 

So far I created a venv and tried to run with `./moodle-dl` but I get this error. 
```
(venv) fulco@Francescos-Air Moodle-Downloader-2 % ./moodle-dl
Traceback (most recent call last):
  File "./moodle-dl", line 4, in <module>
    import moodle_dl.main
  File "/Users/fulco/Desktop/code/Moodle-Downloader-2/moodle_dl/main.py", line 12, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'
```
I also could not find a `requirements.txt`.

**Comment by C0D3D3V** [comment]
If you are using a virtual environment I think, this article can help you: https://techtldr.com/how-to-use-virtualenv-in-python-to-install-packages-locally/
 
 In your virtual environment you can use pip and python just like the normal pip and python. So to install this package you would run: `pip install .`
 
 That is what I tried (seems to work):
 ```
 git clone https://github.com/C0D3D3V/Moode_Downloader_2.git
 cd Moode_Downloader_2
 python -m venv venv
 source ./venv/bin/activate
 pip install .
 venv/bin/moodle-dl
 ```
