### ISSUE TITLE
Log in using a cookies

### ISSUE THREAD

**Issue by zajaczkowski2002** [C0D3D3V/Moodle-Downloader-2#132]
Hi, you can send me the template of the config.json file, I would like to log in using a cookie, not your built-in login process...
Do you have any suggestions? PLS help me

**Comment by C0D3D3V** [comment]
https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Config.json

This tool is based on the moodle mobile API, so it is impossible to log in using a cookie

**Comment by zajaczkowski2002** [comment]
then tell me how to enter the link in the program to log in
https://learnonline.swps.edu.pl/login/index.php**?authCAS=CAS**
authCAS=CAS it is very important parameter

**Comment by C0D3D3V** [comment]
try `moodle-dl --init --sso

**Comment by C0D3D3V** [comment]
Did it help?

**Comment by C0D3D3V** [comment]
I have checked for you if web services are enabled on your Moodle. The web services are enabled, but in your Moodle the login via SSO is only enabled as a second option, which I have already seen in other Moodles. An administrator can decide for each login option separately if the web services are enabled. I assume that in your Moodle the web services are only enabled for the normal login and not with the SSO login, this was also the case in the other Moodles where I have seen a similar situation.

You can get the following json from this URL `https://learnonline.swps.edu.pl/lib/ajax/service.php?info=tool_mobile_get_public_config` (you have to set some extra parameters, I will add this to the moodle-dl soon):

```
[
    {
        "error": false,
        "data": {
            "wwwroot": "https:\/\/learnonline.swps.edu.pl",
            "httpswwwroot": "https:\/\/learnonline.swps.edu.pl",
            "sitename": "Learn Online Uniwersytet SWPS",
            "guestlogin": 0,
            "rememberusername": 2,
            "authloginviaemail": 0,
            "registerauth": "",
            "forgottenpasswordurl": "",
            "authinstructions": "<h4><span style=\"font-size:1.4375rem;color:#FFFFFF;\">Prosimy klikn\u0105\u0107 niebiesk\u0105 belk\u0119 z napisem \"Student | Pracownik\" i\u00a0zalogowa\u0107 si\u0119 swoimi po\u015bwiadczeniami uczelnianymi.<\/span><\/h4><p><span style=\"color:#FFFFFF;font-size:1.4375rem;\">_______________________________________________<\/span><br \/><\/p><p><span style=\"font-size:1.4375rem;color:#FFFFFF;\">Please click the blue button labeled \"Student | Pracownik\" and log in using your university credentials.<br \/><\/span><\/p>",
            "authnoneenabled": 0,
            "enablewebservices": 1,
            "enablemobilewebservice": 1,
            "maintenanceenabled": 0,
            "maintenancemessage": "<p>Poinformujemy Pa\u0144stwa, gdy dost\u0119p do platformy zostanie przywr\u00f3cony.<\/p>",
            "typeoflogin": 1,
            "launchurl": "https:\/\/learnonline.swps.edu.pl\/admin\/tool\/mobile\/launch.php",
            "mobilecssurl": "",
            "tool_mobile_disabledfeatures": "",
            "identityproviders": [
                {
                    "name": "Student | Pracownik",
                    "iconurl": "https:\/\/learnonline.swps.edu.pl\/pluginfile.php\/1\/auth_cas\/logo\/pointing-10.png",
                    "url": "https:\/\/learnonline.swps.edu.pl\/login\/index.php?authCAS=CAS"
                }
            ],
            "country": "0",
            "agedigitalconsentverification": false,
            "autolang": 1,
            "lang": "pl",
            "langmenu": 1,
            "langlist": "",
            "locale": "",
            "tool_mobile_minimumversion": "",
            "tool_mobile_iosappid": "633359593",
            "tool_mobile_androidappid": "com.moodle.moodlemobile",
            "tool_mobile_setuplink": "",
            "warnings": []
        }
    }
]
```

The parameters `enablewebservices` and `enablemobilewebservice` can be taken from this, so the web services are active. However, with `typeoflogin` the normal login is selected as default (type 2 and 3 is SSO login).
