### ISSUE TITLE
Can't use SSO, "Web services must be enabled in Advanced features"

### ISSUE THREAD

**Issue by lapourgagner** [C0D3D3V/Moodle-Downloader-2#134]
Hi, this project seems excellent but cant use it 🙁

OS: W11 Pro
Ver: moodle_dl-2.2.1.6

I only have SSO acces to moodle. When I use `moodl-dl --init --sso` it ask me to go to `https://MYMOODLE/admin/tool/mobile/launch.php?service=moodle_mobile_app&passport=12345&urlscheme=moodledownloader`.
But on this page I got `Web services must be enabled in Advanced features` error.
I am already connected to moodle.

As student I dont have access to any administrative options.
Is there any other way to get the precious token ?

**Comment by C0D3D3V** [comment]
When will moodle-dl work on my Moodle platform?

This project is built on top of the moodle webservice API. This necessarily means that moodle-dl will only work with your Moodle if the webservice interface is also enabled. Administrators usually only enable this if they want to allow the Moodle app on their platform. One way to find out if moodle-dl works on your platform is to test the Moodle app (https://moodle.com/de/app/). If it works, moodle-dl will work.

If the Moodle app does not work, you can ask your Moodle administrator to enable it. The standard features are free for everyone, including universities/schools. 


I will update the readme today (or next week) to make this clear from the start. Additionally I will add the check which is also available in the Moodle app to check if the webservices are activated on the Moodle platform.

**Comment by C0D3D3V** [comment]
See also https://github.com/C0D3D3V/Moodle-Downloader-2/issues/124#issuecomment-966383363

**Comment by lapourgagner** [comment]
Thanks for your precision, I haven't understand the details about the webservices.

Thanks.
