### ISSUE TITLE
Installation Windows11

### ISSUE THREAD

**Issue by treth566** [C0D3D3V/Moodle-Downloader-2#138]
Hi, I tried now multiple times to install the downloader, but can't get it to work on Windows 11, can you give me a detailed step-by-step guide on how to do it? I'm really interested in your script, and it would help me a lot. Thank you :) 

Thanks for reporting a bug 🙌 ❤️

Before opening a new issue, please make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.

Also, be sure to check our documentation first: https://github.com/C0D3D3V/Moodle-Downloader-2
-->

## Avoid duplicates
* [ ] Bug is not already reported in another issue

**Comment by C0D3D3V** [comment]
Install python see https://k0nze.dev/posts/how-install-python-on-windows-11/

Make sure you check the bottom checkbox "Add python to Path" in the second image.
Read the instructions and see if python works as described in the article.

Then open a command prompt:
https://www.isunshare.com/windows-10/4-ways-to-open-command-prompt-in-windows-10.html

then run `pip install moodle-dl`

Then you can run `moodle-dl` as described in the readme.

If this works you can also install ffmpeg as described here, if you also want to download videos: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Installing-ffmpeg

**Comment by treth566** [comment]
hi, thank you for your quick reply, everything works now. I still have an issue with the selection of the courses to download. I can navigate to the second, third, etc course. When i press the space only the first one will be checked/unchecked. Do you have any solution for this ?

**Comment by C0D3D3V** [comment]
Can you send screenshots of this and the corresponding part of the config.json?

**Comment by C0D3D3V** [comment]
I just tested it, works for me. You can navigate with the arrow keys up and down and mark the courses with the space bar. You can confirm your selection with Enter. 

Maybe you prefer to use PowerShell https://www.isunshare.com/windows-10/5-ways-to-open-windows-powershell-in-windows-10.html
It seems to be a bit faster.

**Comment by C0D3D3V** [comment]
@treth566
This seems to be related to this issue 
https://github.com/Kamik423/cutie/issues/26

**Comment by C0D3D3V** [comment]
fixed
