### ISSUE TITLE
Spelling Error in --config

### ISSUE THREAD

**Issue by Aunib** [C0D3D3V/Moodle-Downloader-2#140]
"In the descriptions of files, sections, assignments or courses the teacher can add links to webpages, files or videos. That links can pont to a internal page on moodle or to an external webpage." in `moodle-dl --config` should probably be "In the descriptions of files, sections, assignments or courses the teacher can add links to webpages, files or videos. That links can po**i**nt to a internal page on moodle or to an external webpage."

**Comment by C0D3D3V** [comment]
Thanks I will fix this along with your other issue :)

**Comment by C0D3D3V** [comment]
Done will be in the next release
