### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by lavgup** [C0D3D3V/Moodle-Downloader-2#143]
Please consider adding support for macOS, as this project only supports Linux and Windows as of now.

## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.
Project does not run on macOS

## Describe the solution you'd like
Support added for macOS

## Describe alternatives you've considered
N/A

**Comment by C0D3D3V** [comment]
What does not work on macOS?

**Comment by lavgup** [comment]
> What does not work on macOS?

Running `moodle-dl` or `moodle dl --init` on anything not Windows or Linux throws an error and exits due to [this block](https://github.com/C0D3D3V/Moodle-Downloader-2/blob/main/moodle_dl/utils/readchar/__init__.py#L7).

Please let me know if I am doing anything wrong.

**Comment by C0D3D3V** [comment]
Sorry, was my fault I overlooked that. Test the new version v2.2.1.8

**Comment by C0D3D3V** [comment]
you can update using `pip install -U moodle-dl`

**Comment by lavgup** [comment]
It works, thanks! 😄 

Sorry about not expanding and giving more details on the issue earlier on, I thought this was an intentional design choice.
