### ISSUE TITLE
Never delete files

### ISSUE THREAD

**Issue by lavgup** [C0D3D3V/Moodle-Downloader-2#150]
An option to never delete files, even if they are removed from the Moodle instance.

I'm not too sure about the current behaviour, but [this block](https://github.com/C0D3D3V/Moodle-Downloader-2/blob/5b0057cf053a83ab860f61fce313b3deac6f2691/moodle_dl/state_recorder/state_recorder.py#L625) makes it seem that files are deleted locally if they are removed on Moodle.

This would be good to have more time to revise as many teachers remove content too early.

**Comment by C0D3D3V** [comment]
The code you marked is only our database. 
This does not effect the files you have doenloaded.

But indeed we now have at least a function to deelete outdated files, but that is only explicitly called via an argument. `moodle-dl --delete-old-files`
