### ISSUE TITLE
SSO login

### ISSUE THREAD

**Issue by wasicse** [C0D3D3V/Moodle-Downloader-2#153]
Hi,

I am not able to login Moodle. I got the following error. 

moodle_dl.moodle_connector.request_helper.RequestRejectedError: An Unexpected Error happened on side of the Moodle System! Status-Code: 404
Header: {'Date': 'Tue, 28 Jun 2022 05:13:51 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'Set-Cookie': 'MoodleSession=mhhid96pb8h1sj70380ienikfk; path=/; secure', 'Expires': '', 'Cache-Control': 'private, pre-check=0, post-check=0, max-age=0, no-transform', 'Pragma': 'no-cache', 'Content-Language': 'en-us', 'Content-Script-Type': 'text/javascript', 'Content-Style-Type': 'text/css', 'X-UA-Compatible': 'IE=edge', 'Accept-Ranges': 'none'}
Response: <!DOCTYPE html>

<html  dir="ltr" lang="en-us" xml:lang="en-us">
<head>
    <title>404 Error: File not found</title>
    <link rel="shortcut icon" href="https://moodle.uno.edu/theme/image.php/fordson/theme/1647703172/favicon" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="moodle, 404 Error: File not found" />

I am running the following command:

moodle-dl --sso

and here is my configuration file:

{
    "token": "AAAAAA",
    "moodle_domain": "moodle.uno.edu",
        "moodle_path": "/moodle/"
    }

Any help is appreciated. Thanks.

**Comment by C0D3D3V** [comment]
Try to run `moodle-dl -c` and if that works answer the first question with yes. Then you can answer the reminding questions, and after that try to run `moodle-dl` normaly.

**Comment by C0D3D3V** [comment]
If that does not help, try this: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Set-user-id-and-Moodle-version-number-manually

**Comment by C0D3D3V** [comment]
Also I guess your Moodle Adress is wrong, Are you sure it is moodle.uno.edu/moodle because I get only an error on that page.

**Comment by C0D3D3V** [comment]
Try to run `moodle-dl --init --sso`
and use as moodle URL `https://moodle.uno.edu/`

**Comment by wasicse** [comment]
> Try to run `moodle-dl --init --sso` and use as moodle URL `https://moodle.uno.edu/`0

I have updated the configuration file.

{
    "token": "sssssssss",
    "moodle_domain": "moodle.uno.edu",
    "moodle_path": "/my/",
    "userid": 54132,
    "version": 2021051705
    }

I have also tried all of them. I am having the same error:

  moodle_dl.moodle_connector.request_helper.RequestRejectedError: An Unexpected Error happened on side of the Moodle System! Status-Code: 404

Thanks.

**Comment by wasicse** [comment]
Here is the log and configuration file when I ran moodle-dl command.
[config.zip](https://github.com/C0D3D3V/Moodle-Downloader-2/files/9002247/config.zip)
.
