### ISSUE TITLE
Issues with OpenSSL 3.X.X when server is still running OpenSSL 1.X.X

### ISSUE THREAD

**Issue by p-fruck** [C0D3D3V/Moodle-Downloader-2#154]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

 Using OpenSSL version 3.X.X the following errors might occur in cases where the moodle server does not support OpenSSL v3:

Error message using `requests`:

```
The following error occurred during execution:
Connection error: HTTPSConnectionPool(host='moodle.dhbw-mannheim.de', port=443): Max retries exceeded with url: /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_webservice_get_site_info (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
```

Error message using `urllib`:

```
<urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)>
```

## Steps to reproduce the issue
- Install OpenSSL version 3.X.X (e.g. use a test system/container with Fedora 36 / CentOS 9)
- Execute moodle-dl against a moodle instance that isn't using OpenSLL 3.X.X yet (should be easy to find/host)
- Look at the error message :)

 
```
[Moodle]➡ moodle-dl
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account....
Downloading account information

The following error occurred during execution:
Connection error: HTTPSConnectionPool(host='moodle.dhbw-mannheim.de', port=443): Max retries exceeded with url: /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_webservice_get_site_info (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
```

## Technical details

Any Unix-like system with OpenSSL 3.X.X installed (requires Moodle instance with OpenSSL 1.X.X)

See [this](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled/71646353#71646353) for more details. Notice that installing the recommended `cryptography` version didn't help in my case.

## Expected behavior

This bug should be circumvented.

## Possible Fix
I will provide with a quick fix shortly.

**Comment by C0D3D3V** [comment]
In the new release you can use `--allow-insecure-ssl` to activate this flag
