### ISSUE TITLE
`get_simple_moodle_version()` function signature in `moodle_connector/request_helper.py` is incorrect

### ISSUE THREAD

**Issue by batuhanfaik** [C0D3D3V/Moodle-Downloader-2#159]
## `def get_simple_moodle_version(self) -> float:` function signature on line 238 in `moodle_connector/request_helper.py` is incorrect

The function definition is here:
https://github.com/C0D3D3V/Moodle-Downloader-2/blob/0c798a4b2684ea40eb22dfeadcae99488bda9bda/moodle_dl/moodle_connector/request_helper.py#L238

The function signature expects the function to return `float` however python builtin `strip()` returns `string`. See [related python docs](https://docs.python.org/3/library/stdtypes.html#str.strip) for reference.

## Expected behaviour

Either type `float` should be returned or the signature should be modified

## Possible Fix

Replace line 238 with
```python
def get_simple_moodle_version(self) -> str:
```

because the version is expected and parsed as a string in other files

**Comment by C0D3D3V** [comment]
Thanks for that, but what tool do you use that you noticed that the signature is wrong xD For python the signature is not impirtant it is just for the developers... 

I will merge it later
