### ISSUE TITLE
Typeerror running moodle

### ISSUE THREAD

**Issue by jonas-t-s** [C0D3D3V/Moodle-Downloader-2#166]
Hi there, Thank you for your product! I love using the moodle-Downloade. :D But I run into an issue: 

## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

 I get an error running the Moodle-downloader.It says ` TypeError: Parameters to generic types must be types. Got slice(<class 'int'>, typing.Dict, None). `

## Steps to reproduce the issue

1. Go to the folder, where Moodle-dl is located
2. Execute `moodle-dl`
3. See an error in the terminal (Codeblock below)
4. See, that the `MoodleDownloader.log` hasn't been updated.

```
Traceback (most recent call last):
  File "/usr/bin/moodle-dl", line 5, in <module>
    from moodle_dl.main import main
  File "/usr/lib/python3.10/site-packages/moodle_dl/main.py", line 30, in <module>
    from moodle_dl.state_recorder.offline_service import OfflineService
  File "/usr/lib/python3.10/site-packages/moodle_dl/state_recorder/offline_service.py", line 8, in <module>
    from moodle_dl.moodle_connector.moodle_service import MoodleService
  File "/usr/lib/python3.10/site-packages/moodle_dl/moodle_connector/moodle_service.py", line 22, in <module>
    from moodle_dl.moodle_connector.pages_handler import PagesHandler
  File "/usr/lib/python3.10/site-packages/moodle_dl/moodle_connector/pages_handler.py", line 6, in <module>
    class PagesHandler:
  File "/usr/lib/python3.10/site-packages/moodle_dl/moodle_connector/pages_handler.py", line 15, in PagesHandler
    def fetch_pages(self, courses: List[Course]) -> Dict[int, Dict[int:Dict]]:
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1143, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.10/typing.py", line 1143, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got slice(<class 'int'>, typing.Dict, None).

```
 

I run the MoodleDownloade-2 in verbose mode, but the Log is not reduced. 

## Technical details
 - OS: Manjaro
 - Version Fully updated on Unstable
 - Running Python 3.10.8

## Expected behavior

Downloading some files from Moodle
## Possible Fix
As this issue arises, and it is a type error, I assume that reverting #165 or #164  would fix the problem(May not be feasible). (But I've to note, that I altered some pip packages today, even though I don't think that adding a pip package could create this behavior)

**Comment by C0D3D3V** [comment]
I did not even push the package to pypi... But I guess you are running the main brunch directly from github (maybe from AUR or you downloaded it yourself) 
Thanks for the report. Actually it was the first PRs that I did not test (because I thought they could not break something, and it would have delayed the process till tomorrow). 
@roeekl maybe you can have a look at it?

**Comment by C0D3D3V** [comment]
I think we can just simplify the compex, nested types.

**Comment by jonas-t-s** [comment]
> I did not even push the package to pypi... But I guess you are running the main brunch directly from github (maybe from AUR or you downloaded it yourself)

Yes, I'm downloading it through the AUR.


> Thanks for the report.

Happy to help. Thank you for the tool, I'm using in my daily life.

**Comment by roeekl** [comment]
> https://github.com/C0D3D3V/Moodle-Downloader-2/blob/adc8552744428bf7c67e2f0953b47f41fdce725d/moodle_dl%2Fmoodle_connector%2Fpages_handler.py#L15
> 
> @roeekl I found the problem, you used here an `:` instead of an `,` inside the `[ ]` brackets
> 
> Can you please fix it?

OK, I'll soon make PR

**Comment by C0D3D3V** [comment]
I have already fixed it
