### ISSUE TITLE
SSO can not be generated from mobile app workaround. 

### ISSUE THREAD

**Issue by dgcntrk** [C0D3D3V/Moodle-Downloader-2#170]
Hi there, 
I was using moodle downloader before and we had to set it up with the mobile app but since that has been off the market I can not seem to generate a token for the downloader. It would be amazing if you know any new workarounds for this.

**Comment by C0D3D3V** [comment]
Just for the record, you can still use the moodle desktop app, see:
https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Copy-a-token-from-the-Moodle-app

But If you want I can explain you in a discord call, how to do the normal way, it should work too.

**Comment by dgcntrk** [comment]
it would be amazing if you could please explain on discord. 
doga_canturk#5667
