### ISSUE TITLE
Adding the docker image to the GitHub Container Registry using GitHub Actions

### ISSUE THREAD

**Issue by frereit** [C0D3D3V/Moodle-Downloader-2#171]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.
Currently to use Docker, you have to build the Docker image yourself. This makes in a bit difficult for 'end users' to get started with the tool. GitHub Actions has support for automatic building and deployment of docker images using the GHCR.

## Describe the solution you'd like
Similar to the python publish workflow, a new workflow could be added that simply builds the docker image. It could either be configured to just always run on main, or only run on new tags.

## Describe alternatives you've considered
Building yourself is of course always an options.

## Additional context
If this is something that is wanted, I can easily add and configure a GitHub Action that does exactly that. Let me know and I'll get on it, and open a PR once done.

**Comment by C0D3D3V** [comment]
You are welcome to do a PR. 
I'm open for every improvement. Especially improvments for thr docker workflows are welcome. I guess running it on new tag is fine, since I we currently have no stable main policy (since we have no tests/CI to force one), and I do just push to main....
