### ISSUE TITLE
int() argument must be a string

### ISSUE THREAD

**Issue by juffis** [C0D3D3V/Moodle-Downloader-2#174]
* [ x ] Bug is not already reported in another issue

## Describe the bug

When downloading course information, the process stops every time in same place and gives an error:

> Downloading course information  16/ 17 [KE00BT61-3108 E..| 13337]
> 
> The following error occurred during execution:
> int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

## Steps to reproduce the issue

1. Start moodle-dl
2. Use default settings
3. Downloading starts and stops after a while with the error

 

> Downloading course information  16/ 17 [KE00BT61-3108 E..| 13337]
> 
> The following error occurred during execution:
> int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> 

## Technical details

Ubuntu 22.10 x86_64 
moodle-dl 2.2.2.3 (installed using pip)

## Expected behavior

Downloads complete without errors.

Log:
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/10474910/MoodleDownloader.log)

**Comment by C0D3D3V** [comment]
Interesting bug, strange that only now someone has encountered it. I will fix it and get back to you.

**Comment by C0D3D3V** [comment]
Please test if the new release fixed the problem.

**Comment by juffis** [comment]
> Please test if the new release fixed the problem.

It's fixed now, nice.
