### ISSUE TITLE
deleted files (documentation)

### ISSUE THREAD

**Issue by shoeper** [C0D3D3V/Moodle-Downloader-2#21]
What happens when files where deleted on moodle?

Here an extract from the last run:
```
Public Key Infrastrukturen 2019
-	/files/Public Key Infrastrukturen 2019/Allgemeines/Klausur_Deckblatt.pdf
-	/files/Public Key Infrastrukturen 2019/Allgemeines/Task3Solved.pdf
[..]
```

Fortunately it looks like the files were not deleted (I think downloaded files should never be deleted). So, am I right that this only reflects a database change?

**Comment by C0D3D3V** [comment]
Yes, the changes are only mirrored into the database. The data is still retained. You're right, I haven't written that anywhere. But because it was the same with the old downloader, I have adopted the same behavior. 

I think about the best way to write it into the readme.

**Comment by C0D3D3V** [comment]
As Moodle is currently used much more actively, I'm adding an option to allow deleted files (due to modification, moving or deletion) to be deleted from the local filesystem automatically. As soon as the option is available I will report it here.

**Comment by C0D3D3V** [comment]
I changed my mind, it's too risky a feature for me to have moodle-dl automatically delete files.
