### ISSUE TITLE
No module named 'electrum'?

### ISSUE THREAD

**Issue by MrKrisKrisu** [C0D3D3V/Moodle-Downloader-2#25]
I've tried to get the script to work, but I cannot find any module called "electrum". All Requirements are installed. Do you have further informations?

> user@server:~/Moodle-Downloader-2# python3 main.py --init
>     Traceback (most recent call last):
>       File "main.py", line 15, in <module>
>     from config_service.config_service import ConfigService
>   File "/user/Moodle-Downloader-2/config_service/config_service.py", line 4, in <module>
>     from moodle_connector.results_handler import ResultsHandler
>   File "/user/Moodle-Downloader-2/moodle_connector/results_handler.py", line 5, in <module>
>     from electrum.plugins.coldcard import description
> ModuleNotFoundError: No module named 'electrum'

**Comment by C0D3D3V** [comment]
Where did you download the script from?    Are you using the latest version?    Which system do you use?

**Comment by MrKrisKrisu** [comment]
I've cloned the repository using
> git clone https://github.com/C0D3D3V/Moodle-Downloader-2.git

Tried on Mac OS 10.15.4 and Ubuntu 18.04.4 with Python 3.6 and 2.7.
All Requirements from requirements.txt are installed successfully.

**Comment by C0D3D3V** [comment]
Lol, I see the problem, I've been using Visual Studio code for a couple of weeks now, and it's somehow added a dependency to the code that's completely unnecessary.    I'll fix it soon.

**Comment by MrKrisKrisu** [comment]
I removed the unused Import and the script now works perfectly.

**Comment by C0D3D3V** [comment]
Thank you, I appreciate it very much.
