### ISSUE TITLE
Readline not a module

### ISSUE THREAD

**Issue by martibravo** [C0D3D3V/Moodle-Downloader-2#28]
I have followed the instructions to run this on Python 3.8, and it just doesn't work. 
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Comment by C0D3D3V** [comment]
ow I see readline is not availible in windows. You can just delete the line 8 `import readline` from the main.py file. I will fix this today.

**Comment by C0D3D3V** [comment]
I will leave the issue open till i released a new version.
