### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by marcoscale98** [C0D3D3V/Moodle-Downloader-2#31]
What is this error?

> Moodle Downloader starting...                                                                                      Loading config...                                                                                                  Checking for changes for the configured Moodle-Account...                                                          Download account informationException:                                                                             Traceback (most recent call last):                                                                                   File "D:\Marco\Universita\Moodle-Downloader-2\moodle_connector\moodle_service.                                   py", line 160, in fetch_state                                                                                          userid, version = results_handler.fetch_userid_and_version()                                                     File "D:\Marco\Universita\Moodle-Downloader-2\moodle_connector\results_handler                                   .py", line 30, in fetch_userid_and_version                                                                             result = self.request_helper.post_REST('core_webservice_get_site_info')                                          File "D:\Marco\Universita\Moodle-Downloader-2\moodle_connector\request_helper.                                   py", line 65, in post_REST                                                                                             return self._initial_parse(response)                                                                             File "D:\Marco\Universita\Moodle-Downloader-2\moodle_connector\request_helper.                                   py", line 207, in _initial_parse                                                                                       exception, errorcode, message                                                                                  moodle_connector.request_helper.RequestRejectedError: The Moodle System rejected                                    the Request. Details: moodle_exception (Errorcode: invalidtoken, Message: Token                                    non valido - il token non ▒ stato trovato)                                                                                                                                                                                           During handling of the above exception, another exception occurred:                                                                                                                                                                   Traceback (most recent call last):                                                                                   File "main.py", line 208, in run_main                                                                                changed_courses = moodle.fetch_state()                                                                           File "D:\Marco\Universita\Moodle-Downloader-2\moodle_connector\moodle_service.                                   py", line 213, in fetch_state                                                                                          error))                                                                                                        RuntimeError: Error while communicating with the Moodle System! (The Moodle Syst                                   em rejected the Request. Details: moodle_exception (Errorcode: invalidtoken, Mes                                   sage: Token non valido - il token non ▒ stato trovato))                                                                                                                                                                               The following error occurred during execution: Error while communicating with th                                   e Moodle System! (The Moodle System rejected the Request. Details: moodle_except                                   ion (Errorcode: invalidtoken, Message: Token non valido - il token non ▒ stato t                                   rovato))
> --

**Comment by shoeper** [comment]
The login token is invalid, you have to get and set a new one.

**Comment by marcoscale98** [comment]
how to do it? Maybe the system should do it automatically

**Comment by C0D3D3V** [comment]
You can use `python main.py --new-token`  to generate a new token (add the option `--sso` if you are using single sign on). The downloader can't do that automaticly because ot does not store yout credentials.

**Comment by C0D3D3V** [comment]
Normaly multiple devices can use the same token. For example if you also use the moodle app it should not reject the token. 
Normally a token is also almost never invalid.



But there are circumstances in which a token is discarded more quickly by Moodle.  For example, if you make a lot of requests in quick succession.  For example, if you run the downloader every 5 minutes (and you are enrolled in many courses).  Such behavior can lead to the token being rejected quickly.

My token was not rejected by moodle although I have been running the downloader every 15 minutes for half a year. I think it also depends on how Moodle was set up.

**Comment by marcoscale98** [comment]
> You can use `python main.py --new-token` to generate a new token (add the option `--sso` if you are using single sign on). The downloader can't do that automaticly because it does not store your credentials.

It doesn't ask me the password...
![image](https://user-images.githubusercontent.com/43850400/82066027-2ddbd600-96cf-11ea-9d59-e754f030f063.png)

**Comment by C0D3D3V** [comment]
you are using mingw so you have to run python with winpty.
try: `winpty python main.py --new-token`

**Comment by C0D3D3V** [comment]
Alternatively you can also use the normal Windows Command Prompt (cmd) or the Power Shell.

**Comment by C0D3D3V** [comment]
Can I close this issue?

**Comment by marcoscale98** [comment]
> Can I close this issue?

Yeah, sorry. I resolved
