### ISSUE TITLE
naming problems in file structure with special characters

### ISSUE THREAD

**Issue by m-ango** [C0D3D3V/Moodle-Downloader-2#33]
I don't know the exact cases when it happens but if a moodle section or course has special characters like "/" or ":" it always uses some kind of ID for the folder. 
It names it `"XXXXXX~X"` in alphanumerical chars with the same length.
Is it perhaps possible to parse out these special characters and just name the folder without them?
"Example course 1/2"  to "Example course 1 2" instead of `"XXXXXX~X"` 

Edit: just read the documentation again and yes you can rename the course name but as far as i see you can't rename the sections in the course. I think it would be easier for most people to just let it automatically rename the folder instead of doing it manually since the meaning should be clear even if the special character is missing.

**Comment by C0D3D3V** [comment]
I don't quite follow what's happening.  So you are using in Windows? Under windows some file paths cannot be created, these are filtered in utils/string_tool.py with the function to_valid_name .

**Comment by C0D3D3V** [comment]
Can you give me a concrete example for `XXXXXX~X`?

**Comment by C0D3D3V** [comment]
I'm not sure if it would be worth it if you could rename sections. The usual procedure on moodle is that every week a part is added to a course in a new section. Since you don't know the name of the new section in the pre-field, you can also simply rename the folder after the files have been downloaded, since there is usually nothing new added to the section.

**Comment by C0D3D3V** [comment]
Anyway, I don't have time to implement such a function at the moment, so that you can rename section names. But I will gladly accept pull-requests, if you want to jack in.

But if your problem has other reasons, I can of course fix it.

**Comment by C0D3D3V** [comment]
If I understand your issue correctly, sections/courses are renamed to something completely random alphanumeric. The downloader should not even be able to do that. So this is probably a bug. Are files affected as well?

**Comment by m-ango** [comment]
Thanks for the fast response. 
I ran the script under Linux but the folder was a SAMBA share. But under Linux you also can't have Folder names with a "/".

`VMM7CI~H` is an example. But i think it is completely random identifier. There doesn't seem to be any logic or order behind it. 

No, files are not affected. Since you can't create files with characters like "/" or ":" the bug does not occur. 

I would be very glad if you can just modify the function that modifies the folder name. Just a simple string.replace with from "/" and ":" to " ".
Unfortunately sections are sometimes updated more then once so renaming is not an option. But i think it wouldn't break anything to just replace those characters and be a comfort for a lot of people since it will happen each time a section or course has a special character and renaming manually is tedious.

**Comment by m-ango** [comment]
okay just moved
` name = name.replace('/', '-')
  name = name.replace(':', '-')`
above the `if platform == "win32"`  and it still did not work.

**Comment by m-ango** [comment]
Or perhaps even all characters for all operating systems. 
These small changes should not be important and add a lot of interoperability between operating systems. Especially since a lot of people run this script on a server and access it from different operating systems.

**Comment by C0D3D3V** [comment]
For me it is ok to make the adjustments for all operating systems, there have only been complaints in the past why I adjust the file names although Linux can handle it.  That's why I had only done this for windows.
It's still interesting why these random names come up. Remains a mystery.

**Comment by m-ango** [comment]
1. "/" at least won't work under Linux so you should at least replace that on all systems.
2. Perhaps you can have some kind of user interaction during --init where you ask if they want interoperability if the script is run under Linux. Or a argument in combination with --init which enables replacing for all characters.
3. Yes very strange indeed, it seems to be a OS issue although it is handled on Windows and Linux in the same way.

**Comment by C0D3D3V** [comment]
Good Idea, I put it on my todo list, for now a024569 will be enough.

**Comment by C0D3D3V** [comment]
Your changes are looking good. Thank you very much. As soon as you're ready, you can make a pull-request.

**Comment by C0D3D3V** [comment]
You can now define your own filename character map in the configuration (`filename_character_map`). This is used to filter the paths. 

Windows default:
```
"filename_character_map": {
        "\\": "\uff3c",
        "/": "\uff0f",
        ":": "\ua789",
        "?": "\uff1f",
        "*": "\uff0a",
        "<": "\uff1c",
        ">": "\uff1e",
        "|": "\uff5c",
        "\"": "\uff02"
    },
```
