### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by oOkeOo** [C0D3D3V/Moodle-Downloader-2#34]
I am using WIn10 and got the problem sretting up the config via `main.py --init`
I typed in URL (in my case moodle.rub.de), the username, the password. After a few seconds I get the Error of the topic. In addition it says the Destination Computer refuses the connection establishment.
Is there any solution or am I doing something wrong? I also checked my Firewall and tried to execute it with deactivated firewall...

Thanks for help!

**Comment by C0D3D3V** [comment]
Maybe check your proxy settings in Internet Properties, Connection tab, LAN Settings. moodle.rub.de works fine for me.

**Comment by C0D3D3V** [comment]
And use `https://moodle.ruhr-uni-bochum.de/m/` as url please

**Comment by oOkeOo** [comment]
It worked now. Thanks.
