### ISSUE TITLE
Error while trying to load the Configuration (Win10)

### ISSUE THREAD

**Issue by oOkeOo** [C0D3D3V/Moodle-Downloader-2#35]
I have an Error when I want to change the path.
The Moodle Downloader (all files, also config) is in `D:\Uni\Moodle\Moodle-Downloader-2-master`.
I want to set the path to Moodle typing `python D:\Uni\Moodle\Moodle-Downloader-2-master\main.py --path D:\Uni\Moodle\`. (Powershell)
Then he obviously has problems to find the config. Where is my fault?

**Comment by C0D3D3V** [comment]
Did you put the config in the path  `D:\Uni\Moodle\` ?

**Comment by C0D3D3V** [comment]
There are currently two ways to change the location where the files are downloaded. The configuration file must be located in the folder in which the download takes place. This will change when #17 is finished. 

* Either you copy all downloaded files and the configuration into a folder of your choice and open a terminal in it. In this terminal you can open/run the Moodle downloader, which is located in a different folder. 

* Or you are in the folder where the Moodle donwloader is located and you call the downloader with the --path function. The path can be any other folder where the configuration file is located and where the data is downloaded.
