### ISSUE TITLE
[Feature Request] Download files inside sub-structures (databases).

### ISSUE THREAD

**Issue by verone0001** [C0D3D3V/Moodle-Downloader-2#40]
Hello!

I'm enrolled in a course where the excercises are not uploaded directly into a structure (_https://the_domain/moodle/course/view.php?id=3588_) but in a sub-structure (_https://the_domain/moodle/mod/data/view.php?id=169908_) as it can be seen in the following image:

![image](https://user-images.githubusercontent.com/30376241/86128053-38073780-bab7-11ea-8b4f-112d79595c9f.png)

Said that, when configuration is done and executed, it doesn't download the sub-structure where files are located.
Is it possible to add that feature? It will be much appreciated!

**Comment by C0D3D3V** [comment]
:D I never saw someone using the database module. I will have a look on it.

**Comment by C0D3D3V** [comment]
Seems at first view to be easy to implement. It is only problematic if the database contains a lot of data, but this can be optimized over time. I will do the first steps in the next days and report the status here.

**Comment by verone0001** [comment]
Good to know! In this case, the database contains only 53 C/C++ files which are around ~3-7 KB. Each one containing a little description (which I don't really care). I will be following the updates 👍.

**Comment by C0D3D3V** [comment]
I have implemented the desired function as you can see here:  https://github.com/C0D3D3V/Moodle-Downloader-2/compare/e21eaf13...56aa81ae
The implementation is very primitive and not optimized at all. Currently, all files of the databases are simply downloaded. Feeback is very welcome :)

I hope this is the way you wanted it :) I wrote this just for you. I tested it with a test Moodle, because our university does not use the database module at all. 

You have to activate the download either by adding `"download_databases": true,` to the configuration or by adding `python main.py --config` and activating the function at the right place.

**Comment by verone0001** [comment]
Great to read good news! I'll be testing this and giving you some feedback of course!

**Comment by verone0001** [comment]
So as far as I could see, making it the interactive way (`Do you want to make additional configurations now? (Y/N)`) displays the following error:

![image](https://user-images.githubusercontent.com/30376241/86501802-da9f0f00-bd72-11ea-94b2-bef7c13b9dd7.png)

Right after that one, I traced it and noticed that `fetch_userid_and_version` wasn't an attribute from such line, so I added it and tested it again, but got this error:

![image](https://user-images.githubusercontent.com/30376241/86501841-441f1d80-bd73-11ea-89e2-40357b809d2a.png)

so I traced it down again (this time to the main `ResultsHandler` definition) and noticed that `fetch_userid_and_version` isn't implemented into such class, cutting the workflow.

Now, manually adding `download_databases: true` inside `# create default settings` from `config_service.py` sections `_set_options_of_courses` and `_change_settings_of`(this one just in case), displays me the following error:

![image](https://user-images.githubusercontent.com/30376241/86502434-69168f00-bd79-11ea-8b40-fc776912c175.png)

cutting the workflow again (as the previous one, maybe the implementation is missing in such file).



Hope this feedback is somehow useful!

**Comment by C0D3D3V** [comment]
Did you used the latest code?

**Comment by verone0001** [comment]
Yes, and I verified it twice just in case.

**Comment by C0D3D3V** [comment]
That is strange because line 32 does not exist in the config_service.py from the first exception.
But the third exception seems real, i will fix it later.

**Comment by C0D3D3V** [comment]
you can change line 237 in moodle_service.py to: 
`course_databases = databases.get(course.id, {})`

this could fix it. I can push it in a few hours, when I'm back home...

**Comment by C0D3D3V** [comment]
The feedback was of course very helpful, thanks for that. I hope the last update has fixed the bug. 

Your first two exceptions cannot be based on the last code base. Please make sure that you really use the latest version of the code.

**Comment by verone0001** [comment]
I have just arrived at home and tested it the interactive way and is working like a charm! I don't know why I got those errors though, but after your latest commit I downloaded it all again.
Thanks for this great update, I know the database module could be a bit weird to use in moodle (it's the first assignement who had one actually), but it is downloading all the files correctly. The description for each one is not necessary to me.
Keep on this amazing project 🔥.

**Comment by C0D3D3V** [comment]
Thank you very much :) It's an honor. 
If I don't know what to do with my time I'll see if I can get the descriptions and links from the databases. But for now it should be ok without them.

If there is anything else, you can just open a new issue.
