### ISSUE TITLE
Cannot download .pdf files

### ISSUE THREAD

**Issue by IcaroStumpf** [C0D3D3V/Moodle-Downloader-2#42]
Wonderful tool you got there, thanks for it.
I can download videos hosted on you tube with the latest builds, but it simply skips .pdf (and zipped files, I guess...). Also, if I recall correctly, I did not have this problem in version 1.6.
Thanks for your time!

**Comment by C0D3D3V** [comment]
Are you using Windows?

**Comment by IcaroStumpf** [comment]
Yes, Windows 10 64-bit version 2004

**Comment by C0D3D3V** [comment]
And with pdf files you mean external files or files hosted on moodle?

**Comment by IcaroStumpf** [comment]
Those hosted on moodle

**Comment by C0D3D3V** [comment]
I will test if I can reproduce it.
On linux it works for me.

**Comment by IcaroStumpf** [comment]
I just tried it in WSL 2, but I get the same problem. It downloads files with .md format (I really don't know what that is), but it does not download .pdf and .zip files.

**Comment by C0D3D3V** [comment]
I tested it under windows. All files are downloaded as usual. 

You have to give me more details, what exactly is missing, what kind of moodle you use, anything you think might be helpful. 

Can you send some sample links from files you think won't download.  And can you check if they haven't already been downloaded and you have unknowingly deleted them? You can check this with the `--manage-database' function.

.md files are the description files. They have been converted from HTML to [Markdown](https://en.wikipedia.org/wiki/Markdown) to make them easier to read in any text editor.

**Comment by C0D3D3V** [comment]
If you do not want to download Youtube videos you can deactivate this in the [settings](https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Download-(external)-linked-files).

**Comment by C0D3D3V** [comment]
And check the `MoodleDownloader.log` file for errors

**Comment by IcaroStumpf** [comment]
Here is the moodle of my University: https://moodle.pucrs.br/

I just tried again:
1) Deleted Moodle downloader 1.9 folder
2) Ran the setup again
3) Disabled download of linked files (to save time)
4) The folders are created correctly and the md files are (it downloads html too), but not a single .pdf file is there
5) I recall not having this problem in version 1.6
6) I attached the log
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/4925501/MoodleDownloader.log)

**Comment by C0D3D3V** [comment]
Please try to use `--skip-cert-verify`, i think you get the 403 errors for another reason but maybe it helps.

**Comment by IcaroStumpf** [comment]
No luck :(
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/4925598/MoodleDownloader.log)

**Comment by C0D3D3V** [comment]
Mm, ok, too bad.  Thanks for your detailed report.  And thanks also for your super feedback.  I can do something with that.  Maybe I find a difference between what I did differently in 1.6, at the point where the error occurs.

**Comment by IcaroStumpf** [comment]
Thank you for your time. PM me in case you need anything

**Comment by C0D3D3V** [comment]
Send me an email or add me to skype username is my email). 
Since version 1.6 the download mechanism has not changed, we need to dig deeper together. I will send you later instructions what you can prepare for a debugging session.

**Comment by IcaroStumpf** [comment]
Btw, I had a colleague of mine try and do the same text and he gets the same results :( 
Maybe the problem has to do with the particular version of Moodle my University uses.

**Comment by IcaroStumpf** [comment]
Just tested version 1.6

1) got the error: (which did not happen with version 1.9)
                 File "main.py", line 8, in <module>
                 import readline
                 ModuleNotFoundError: No module named 'readline'
2) Ran python -m pip install pyreadline
3) Ran python main.py --init
4) python main.py
5) the folder was created, but only url were downloaded (not .pdf or .zip files)
6) I attached the log
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/4926853/MoodleDownloader.log)

**Comment by C0D3D3V** [comment]
Maybe you used 1.5 before. From 1.5 to 1.6 I changed the download function completly.

**Comment by IcaroStumpf** [comment]
Just tried it.
No luck again :(
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/4927040/MoodleDownloader.log)

**Comment by IcaroStumpf** [comment]
Maybe I am mistaken in affirming that it used to work before.
With this chrome extension though, https://chrome.google.com/webstore/detail/moodle-downloader/ohhocacnnfaiphiahofcnfakdcfldbnh, I can download all files, but not the videos from the links (as your latest version can).

**Comment by C0D3D3V** [comment]
Don't worry, we'll figure out what the problem is. Just because you're the first to report it doesn't mean you're the only one. 

I actually thought about it if it's just your moodle, but that's almost impossible because I tested the links from your logs and I can visit those links without getting the 403 errors. You can try it yourself if you get a 404 error when you go to the link or just a token error: https://moodle.pucrs.br/webservice/pluginfile.php/2757440/mod_resource/content/3/Trabalho_2020_1.pdf?forcedownload=1

If you are really interested in finding the bug, please follow these instructions to set up a debug environment so we can find the bug together:
https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Development-Environment

**Comment by IcaroStumpf** [comment]
1) Just a token error
2) I followed the steps, but I stumbled across this:
![image](https://user-images.githubusercontent.com/57532011/87606886-75cca880-c6d2-11ea-9ba1-d9930f923469.png)

**Comment by IcaroStumpf** [comment]
I mean, the json file is there, I renamed it to config.json instead of settings.json to no avail:

![image](https://user-images.githubusercontent.com/57532011/87606965-a1e82980-c6d2-11ea-8c70-7e2e8d02cc0c.png)

**Comment by C0D3D3V** [comment]
`settings.json` is the configuration of visual studio code. `config.json` is the configuration of your moodle account. Two diffrent files in two diffrent directories. I will rewrite this part in the tutorial tomorrow.

**Comment by IcaroStumpf** [comment]
Ok. I edited the config.json file in my work folder, but I'm getting the same error

**Comment by C0D3D3V** [comment]
By the way, please thest the latest code from here: https://github.com/C0D3D3V/Moodle-Downloader-2/archive/master.zip

I added a user agent to the download process

**Comment by C0D3D3V** [comment]
2519edcbf9354e90a3b5bc93861d77b376805cf8 fixed the problem
