### ISSUE TITLE
way to download deleted folder

### ISSUE THREAD

**Issue by HumHongeKamyaab** [C0D3D3V/Moodle-Downloader-2#43]
Is there any way to download accidentally deleted course folder without downloading everything else (or new configuration).
$ python3 main.py
doesn't support it.

**Comment by C0D3D3V** [comment]
There are several ways to re-download a course folder that was accidentally deleted. 

I think the best option is to copy your configuration to another folder and use `--config` to select only the course you want to download again, don't forget to run the downloader in the new folder.  Finally you can copy the downloaded folder back into your old main folder.

Alternatively, you can look at thee
 `--manage-database` option, or use a Sql-Lite browser to delete entries from the database which should be downloaded again.

**Comment by HumHongeKamyaab** [comment]
@C0D3D3V Thanks for the reply.
I was thinking of a command line option like --checkout  as  `git checkout` and --status as `git status` in the` main.py`, so that it can be done `git` way.

**Comment by C0D3D3V** [comment]
I think currently it is not a good idea to add git to the project. It's not hard to wrap the script to create a new commit after each execution, if new data is available. In general, this brings a lot of overhead. But please create a new issue if you think it makes sense to add a function that automatically creates git commits (and initializes a repo if necessary).
