### ISSUE TITLE
[Feature Request] Download links listed in descriptions

### ISSUE THREAD

**Issue by HumHongeKamyaab** [C0D3D3V/Moodle-Downloader-2#44]
Is there way to automatically download all the internal moodle links from course main page.
for eg following type of links are present in ".md" file, but these pdf files are not downloaded. 
https://moodle.foouniv.com/webservice/pluginfile.php/2665772/course/section/243653/foo2.pdf
https://moodle.foouniv.com/pluginfile.php/1540393/mod_label/intro/foo1.pdf

**Comment by C0D3D3V** [comment]
By the way, the first link could already be downloaded now, the descriptions would only have to be parsed for links. 
To download the second link we have to finish #41 first. As soon as #41 is finished, I will go on this issue.

**Comment by C0D3D3V** [comment]
Links are now recognized well enough in descriptions and downloaded accordingly if possible. Links of the 2nd kind are still missing, therefore #41 must be finished.

**Comment by C0D3D3V** [comment]
Ok, we are ready for a test! Make sure you also set a `privatetoken` in the `config.json`.

Use the `issue-41` branche (https://github.com/C0D3D3V/Moodle-Downloader-2/archive/issue-41.zip)

**Comment by C0D3D3V** [comment]
I now close this issue. If something is missing, you are welcome to open a new issue.
