### ISSUE TITLE
youtube-dl parsing issue

### ISSUE THREAD

**Issue by nkfs** [C0D3D3V/Moodle-Downloader-2#47]
FYI - I'm running on Issue-41 build due to SSO / cookie issues.

I'm not receiving any other errors aside from the following youtube-dl excerpts.  It does not show me the actual URL of where it is trying to go, but I know the youtube links in my lessons are public.  I'm wondering if it is a parsing issue or something else.  I'm running the latest version of youtube-dl from pip, on linux.

Thanks

Total:   0%          794/      133314kb T0:   0% T1:   0% T2:   0% T3:   0% T4:   0%
youtube-dl: ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>

youtube-dl: ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>

Total:   0%          794/      133314kb T0:   0% T1:   0% T2:   0% T3:   0% T4:   0%

**Comment by C0D3D3V** [comment]
Is there nothing more in the log?

**Comment by C0D3D3V** [comment]
maybe try this https://stackoverflow.com/a/17415168

**Comment by C0D3D3V** [comment]
And please look in the log file if there is anything of interest.

**Comment by nkfs** [comment]
Nothing is recording in the log file, the snippet in the original post was from stdout. I looked at the stackoverflow link, I don't really understand the python bits, but I can resolve the youtube links in my terminal using nslookup / ping.

**Comment by C0D3D3V** [comment]
try to use yotube-dl directly in terminal like:

`youtube-dl -v https://www.youtube.com/watch?v=ZBeUQbkDzI4`

**Comment by C0D3D3V** [comment]
the stackoverflow link, just says that you should check your environment variables for proxy settings (link `http_proxy`). But I think you didn't setup such variables.

**Comment by C0D3D3V** [comment]
And maybe check your host file if you blocked any domains...

**Comment by nkfs** [comment]
no issues with running youtube-dl directly.  Also my host file is fine, and I can see the dns request go out successfully through my dns server.

**Comment by C0D3D3V** [comment]
You can run the downloader now with the new option `--verbose`. Maybe this will help us find out what is happening.

**Comment by C0D3D3V** [comment]
Maybe send the log via mail. You find my mail in my profile.

**Comment by C0D3D3V** [comment]
You may send me the log file by mail.

**Comment by C0D3D3V** [comment]
I think this is fixed in the latest version!
