### ISSUE TITLE
Generate a new token inline

### ISSUE THREAD

**Issue by federicotorrielli** [C0D3D3V/Moodle-Downloader-2#52]
Would be great for automated systems to have the command `moodle-dl --new-token username password` instead of being a triple step command, so my server can re-generate the token when it's not working anymore.

**Comment by C0D3D3V** [comment]
Hope this is in your interest: 

```
moodle-dl -nt -u student -pw moodle
[The following Credentials are not saved, it is only used temporarily to generate a login token.]
New Token successfully saved!
```

**Comment by federicotorrielli** [comment]
This is perfect, thanks!

**Comment by C0D3D3V** [comment]
With wrong user data the script ends with error code 1
```
moodle-dl -nt -u student -pw moodlea 
Login Failed! (The Moodle System rejected the Request. Details: Invalid login, please try again (Errorcode: invalidlogin, Stacktrace: None, Debuginfo: None, Reproductionlink: None)) Please try again.
```

**Comment by federicotorrielli** [comment]
I'll reopen the issue so people can notice the new command until the new README

**Comment by federicotorrielli** [comment]
Commit 049110888809e9b398d5ffdb64b9cb90c930cf42 closes the issue, thanks.
