### ISSUE TITLE
Is my Moodle not supported?

### ISSUE THREAD

**Issue by ColdMeekly** [C0D3D3V/Moodle-Downloader-2#53]
## Avoid duplicates
* [ x ] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.
My university is using moodle with SSO however, they don't have the moodle downloader plugin enabled meaning I cannot perform the automatic or manual SSO sign in methods.

## Describe the solution you'd like
Would be fantastic if there was another method of getting the token.

## Describe alternatives you've considered
I haven't analyzed how SSO works, so I can't help here.

**Comment by C0D3D3V** [comment]
There is only one way to find out if your university is supported: If you can use the Moodle app for Android(IOS, then this downloader is also supported.

If you can use the moodle App you can try to obtain a token fully manually as explained here: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Obtain-a-Token

There are only two options for setting up API support for Moodle with SSO Either the default method which I have completely implemented in the downloader, or with the help of a plugin (no one has reported this yet).

**Comment by C0D3D3V** [comment]
A link to your Moodle would be very helpful.

**Comment by C0D3D3V** [comment]
The SSO process has not changed since Moodle 3.8.2 so this is not related to the moodle version.

**Comment by ColdMeekly** [comment]
> There is only one way to find out if your university is supported: If you can use the Moodle app for Android/IOS, then this downloader is also supported.
> 
> If you can use the moodle App you can try to obtain a token fully manually as explained here: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Obtain-a-Token
> 
> There are only two options for setting up API support for Moodle with SSO Either the default method which I have completely implemented in the downloader, or with the help of a plugin (no one has reported this yet).

Just tried using the mobile app, couldn't get logged in. It simply refused all possible variants of my credentials. Here's my moodle: https://moodle.royalholloway.ac.uk/

Also here's the screenshot what I see in the network log: 
![image](https://user-images.githubusercontent.com/20516479/95689501-19155700-0c09-11eb-8f97-aa73855462e3.png)

**Comment by C0D3D3V** [comment]
Mm, sorry for you. On your Moodle the Moodle app is completely disabled. If the Moodle app is disabled, this downloader will not work because it uses the app's interface. 
By the way, this is a very nice university :)

You can contact the person responsible (I think thats the email at the top of this website: https://itss.royalholloway.ac.uk/) and ask them to consider activating the Moodle app. This would not only allow you to use this downloader, but would allow the many students to use the app, which in itself has many great features.The function costs the university something, so they like to think twice about activating it.

**Comment by C0D3D3V** [comment]
So the problem is not the SSO, but the costs the university wants to save.

**Comment by ColdMeekly** [comment]
Damn what a shame. Do you think it'd be possible to add in a feature to temporarily login using a cookie to download content once?

**Comment by C0D3D3V** [comment]
This would require you to rewrite everything in the folder moodle_connector. This downloader is completely based on the Moodle API (which universities usually only enable for the Moodle app). 

I also can't recommend my old downloader (https://github.com/C0D3D3V/Moodle-Downloader), which doesn't use the API but parses the website so a cookie would work. But currently with the old downloader it is not possible to use a cookie, and the type of SSO your university uses is not implemented. 
If I have a lot of time in the far future I could write a moodle_connector that does not use the API... but not this year.

**Comment by ColdMeekly** [comment]
Alright, I appreciate your help. It's a real shame I couldn't get to try your project out, I'll see if I can master something up maybe.
