### ISSUE TITLE
it doesn't download all the videos on the page

### ISSUE THREAD

**Issue by marcoscale98** [C0D3D3V/Moodle-Downloader-2#54]
Look at this example:
![foto1](https://user-images.githubusercontent.com/43850400/96086246-522c2080-0ec2-11eb-94c5-3e73622125ad.png)
This is the section of a course. Each link leads to a moodle page where there are several videos and comments. 
![foto3](https://user-images.githubusercontent.com/43850400/96086441-a7683200-0ec2-11eb-849d-cf0a58ef691b.png)
But the program downloads only the first video as you can see in the next photo.
![foto2](https://user-images.githubusercontent.com/43850400/96086367-8273bf00-0ec2-11eb-998b-6f67a75395bd.png)

**Comment by C0D3D3V** [comment]
Which version of moodle-dl are you using? It would be advisable to use the latest version.

**Comment by C0D3D3V** [comment]
After you update to the new version, for example with: `pip install -U moodle-dl` you can remove the pages from the databes with `moodle-dl -md` so they get redownloaded (or use an sql-lite Database Viewer to remove the entries).

**Comment by marcoscale98** [comment]
Ok, i update to the latest version but, i don't know why, i see only 2 of 4 courses when i run `moodle-dl -md`
![image](https://user-images.githubusercontent.com/43850400/96095012-54947780-0ece-11eb-8e87-8d55e97d37b5.png)
![image](https://user-images.githubusercontent.com/43850400/96095027-5bbb8580-0ece-11eb-92eb-64b918d5a3d6.png)

**Comment by C0D3D3V** [comment]
It shows only the courses you have selected in your configuration

**Comment by C0D3D3V** [comment]
And only courses where files are missing

**Comment by C0D3D3V** [comment]
thats why you have to move the videos away

**Comment by marcoscale98** [comment]
> thats why you have to move the videos away

Thank's, now it's perfect.
