### ISSUE TITLE
Download videos/files from particular websites like Zoom automatically

### ISSUE THREAD

**Issue by HumHongeKamyaab** [C0D3D3V/Moodle-Downloader-2#55]
Some professors post video links of zoom, universityspecificyoutube etc on moodle. Often these links require authorization, which can be handled by `--cookies` option in `youtube-dl` or `--load-cookies` option in `wget`.
Is there a way to automatically force download these links posted on moodle.
User can specify pattern of the links and software to use for them, something like,
dropbox -> wget
youtube -> youtube-dl
zoom -> wget
universityspecificyoutube -> youtube-dl
PS: the cookies can be set using https://github.com/dandv/convert-chrome-cookies-to-netscape-format

**Comment by C0D3D3V** [comment]
Currently there are two solutions to the problem. If `download_also_with_cookie` is enabled in the configuration, then a file called `Cookies.txt` is created in the download folder. There you can simply add your zoom cookie. Note that this file will be automatically deleted if your Moodle refuses to create a Moodle cookie. 

If this option is disabled you can override the youtube-dl option and create your own `Cookies.txt`. 
Just add the following in the `config.json`:

```
"youtube_dl_options": {
        "cookiefile": "Cookies.txt"
    },
```

**Comment by HumHongeKamyaab** [comment]
Issue is not about cookies, that can be managed externally in youtube-dl and wget config files in home folder.
The main thing is 
```
Is there a way to automatically force download specific website links posted on moodle.
User can specify pattern of the links and software to use for them, something like,
dropbox -> wget
youtube -> youtube-dl
zoom -> wget
universityspecificyoutube -> youtube-dl
```

**Comment by C0D3D3V** [comment]
currently every link is just tried to be downloaded with youtube-dl and if youtube-dl can't find any videos, it downloads it manuly (just like wget, it is called urllib2).

The first option I mentioned above does not work at all. I had it wrong in my head. I will fix this as soon as possible to make this possible.

**Comment by C0D3D3V** [comment]
Have you set `download_linked_files` to true?

**Comment by C0D3D3V** [comment]
Can you send me the log, from downloading this file? So delete the desktop file and remove it from the database with `moodle-dl -cm` 
Then redownload it with `moodle-dl -v` and send me the new log.

**Comment by HumHongeKamyaab** [comment]
I am using `master` moodle-dl

> Have you set `download_linked_files` to true?

yes, I am using `master` branch of moodle-dl

**Comment by C0D3D3V** [comment]
did you test the link with youtube-dl? Can youtube-dl even download the link?

**Comment by C0D3D3V** [comment]
I will look up if the config file of youtube-dl is even used if I call it in my script... I think you have to use the secend option I told you above.

**Comment by HumHongeKamyaab** [comment]
> did you test the link with youtube-dl? Can youtube-dl even download the link?

You are right, youtube-dl can't download this link for me. I need to check my cookies config.

But still I have issues in automatically downloading videos links of zoom. Actually youtube-dl is not supporting zoom links itelf. Its not a issue of moodle-dl

**Comment by C0D3D3V** [comment]
youtube-dl will ignore yout system/home configuration file, because it is not run externaly but it is integrated in the moodle-dl. 

You have to send me some test links. I will see what we can do. I can write an extractor for youtube-dl so that the links get downloaded too. But I never saw a Zoom Link with a download option... so send me one. Via mail if you want, or telegram: c0d3d3v is my username

**Comment by C0D3D3V** [comment]
Look at this wiki entry, how to use cookies for downloading. https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Use-cookies-when downloading

**Comment by C0D3D3V** [comment]
So what other wishes do you have? I don't quite understand your question and without the information I asked for I can't do anything else.

**Comment by C0D3D3V** [comment]
I will add the zoom extractor to moodle_dl. It will be in the next release.
