### ISSUE TITLE
Download BigBlueButton lessons

### ISSUE THREAD

**Issue by federicotorrielli** [C0D3D3V/Moodle-Downloader-2#57]
## Avoid duplicates
* [✔️] This enhancement request has not already been raised before

## Feature Request
I'd like the downloader to download BigBlueButton (an open-source webconferencing suite) lessons.
Usually lessons are grouped like the image below:

![immagine](https://user-images.githubusercontent.com/31370059/96877621-330d3000-147a-11eb-8fa7-4418c59d876c.png)

And redirect to a link like https://SITEWITHMOODLE/mod/bigbluebuttonbn/view.php?id=143127#

## Solution?
The main issue with BBB is that there is more than 1 recordings when it comes to lessons. Usually professors record themselves with a cam and a presentation PDF sliding. Being only the webcam a downloadable video, I find this very hard to implement this enhancement, but I'm proposing y'all.

![immagine](https://user-images.githubusercontent.com/31370059/96878192-d3635480-147a-11eb-95ce-15c814e51458.png)

As you can see (i removed the professor webcam on the right, but you can imagine), there is a playback control, but it's not related to a video, rather than a complicated presentation slider + webcam video as I previously said.

**Comment by C0D3D3V** [comment]
To download from BBB we could include this extractor https://github.com/ytdl-org/youtube-dl/pull/25092
But as it looks like your university uses some kind of special plugin to display the BBB lessons inside a  Moodle Course.  The `bigbluebuttonbn` mod you mentioned, is the mod displayed in the moodle app?

**Comment by C0D3D3V** [comment]
In general I think because BBB uses such a special format it is probably better to use a special solution. Youtube-dl can not give a good result. But I found some promising solutions on githuba. For example https://github.com/trahay/bbb-downloader

**Comment by C0D3D3V** [comment]
What would be your desired result?

**Comment by federicotorrielli** [comment]
This is exactly what I meant https://github.com/trahay/bbb-downloader in the section "Capturing the full playback"

**Comment by federicotorrielli** [comment]
But, I mean, it's very tricky and requires a "more than just Python" solution

**Comment by federicotorrielli** [comment]
Well, if we got the recordings, it's just good to have them. See "Downloading already available recordings" in the page.

**Comment by C0D3D3V** [comment]
Send me a link to one of the lessons please. If you don't want to share it here, send it via mail or telegram (c0d3d3v) so I can try if it is possible to get a good result with youtube-dl. 
I will not include https://github.com/trahay/bbb-downloader in this moodle-dl, that will make no sense at all. And recording a firefox session can also easily done with obs ...

**Comment by federicotorrielli** [comment]
Don't worry, they are open to the public: https://bbb-cluster.di.unito.it/playback/presentation/2.0/playback.html?meetingId=bd788745741ab787621c0dafa69a06ef91c0f02d-1603349301553

**Comment by C0D3D3V** [comment]
With the extractor ytdl-org/youtube-dl#25092 you would get the webcam+sound. 

So that the sound is connected with the presentation is much more effort needed. I have some ideas how I would implement this. But I wouldn't implement it in the moodle-dl, that's too far away from the topic. I could build a separate tool which creates a video from the data of the presentation with the help of ffmpeg. That's not difficult, I think I'll try it, because this semester I will also have a lecture that uses BBB. If I can report a success, I will inform you here. 


If you find Webcam+Sound helpful for now, I can add the Extractor.

**Comment by federicotorrielli** [comment]
Don't worry, I'll use the bbb-downloader repository for now, until we got a better separate tool, which I consider it a better idea. If you make a new repository, please share it here so I can help you out with the programming.

**Comment by federicotorrielli** [comment]
Wait, what about https://github.com/createwebinar/bbb-download ?

**Comment by C0D3D3V** [comment]
Yes I saw that. I thought I will fork it and change it so that you can pass a link to it and then it creates a mp4

**Comment by C0D3D3V** [comment]
I did not get very far so far... ...but I started: https://github.com/C0D3D3V/bbb-dl

**Comment by C0D3D3V** [comment]
Do you have an example where the professor shares his screen?

**Comment by federicotorrielli** [comment]
Yeah: https://bbb-cluster.di.unito.it/playback/presentation/2.0/playback.html?meetingId=5d9131dc7fd145ee063f4400305e7fe018b7032c-1601622033965

**Comment by C0D3D3V** [comment]
youtube-dl was taken down an hour ago :(
But the downloader is ready

**Comment by federicotorrielli** [comment]
At least I have my current offline copy, but, what a shame. Thanks anyway!
