### ISSUE TITLE
This package is now available on the AUR!

### ISSUE THREAD

**Issue by marioortizmanero** [C0D3D3V/Moodle-Downloader-2#58]
Hello! I am an Arch Linux user that really enjoyed using this package. We have the [AUR](https://aur.archlinux.org/) (Arch Linux User Repository), with lots of lesser known packages and unofficial to the distro. It's relatively easy to upload one in there, so I wrote a PKBUILD and uploaded it as [moodle-dl-git](https://aur.archlinux.org/packages/moodle-dl-git/).

I decided to install it directly from this source (hence the `-git` suffix) instead of the [releases page](https://github.com/C0D3D3V/Moodle-Downloader-2/releases) because there seem to be lots of releases and I don't have enough time to fully maintain it. I assumed that the master branch is more or less stable, though.

I just wanted to let the maintainers know about this. If you want to modify anything in the package I uploaded, do let me know. I can also add you as co-maintainers if you use this distro as well and are interested in helping out.

I partly opened this issue so that this can be added to the README for future Arch users, which prefer using the AUR than pip to install packages. Not sure if other distros have this program uploaded to their repositories, but it could be a new section in the "Installation" part.

**Comment by C0D3D3V** [comment]
I love it! I thank you very much. I also use Arch Linux and I know the trubble with the pip packages that can conflict ^^ 
I will add it to the README :)

**Comment by C0D3D3V** [comment]
If you want you can add me as co-maintainer. My username is c0d3d3v as usual :D Then just tell me what to do after each release.

**Comment by marioortizmanero** [comment]
Sure! I've just added you. The `-git` package doesn't need much maintainance, other than when you modify the dependencies or build process.

**Comment by C0D3D3V** [comment]
ok perfect :) Thanks for your work!
