### ISSUE TITLE
Generating .url files on macOS instead of .desktop files

### ISSUE THREAD

**Issue by jnnkB** [C0D3D3V/Moodle-Downloader-2#61]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

On macOS this programm generates .desktop files, as macOS is a unix system. But macOS does not support .desktop files. Instead this tool should produce .url files like on windows since they are supported. If you would like I could open a PR for this.

**Comment by C0D3D3V** [comment]
Oh, thanks for the information :+1: 

I would welcome a pull request :) Otherwise I will change that as soon as I have time again.

**Comment by jnnkB** [comment]
Thanks 🙏
