### ISSUE TITLE
Hide moodle invalidtoken raised exception

### ISSUE THREAD

**Issue by marcoscale98** [C0D3D3V/Moodle-Downloader-2#64]
I think it's better to hide the moodle_Exception invalidtoken. 
` raise RuntimeError('Error while communicating with the Moodle System! (%s)' % (error))
RuntimeError: Error while communicating with the Moodle System! (The Moodle System rejected the Request. Details: moodle_exception (Errorcode: invalidtoken, Message: Token non valido - il token non è stato trovato))`
This exception is thrown when the token has expired and in my opinion the user should be told how to create a new token.
You could write something like this:
`Token expired. To create a new one run
moodle-dl -nt -u USERNAME -pw PASSWORD`

**Comment by C0D3D3V** [comment]
I think this is a very good idea. I'm very busy with my studies at the moment, it will take me a while to implement it.

**Comment by C0D3D3V** [comment]
What do you think, is the following error better for you?

```
moodle-dl                                              
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account....
Downloading account informationException:
Traceback (most recent call last):
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/moodle_service.py", line 232, in fetch_state
    userid, version = first_contact_handler.fetch_userid_and_version()
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
    result = self.request_helper.post_REST('core_webservice_get_site_info')
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 126, in post_REST
    json_result = self._initial_parse(response)
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 262, in _initial_parse
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/main.py", line 227, in run_main
    changed_courses = moodle.fetch_state()
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/moodle_service.py", line 297, in fetch_state
    raise RuntimeError('Error while communicating with the Moodle System! (%s)' % (error))
RuntimeError: Error while communicating with the Moodle System! (Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD")

The following error occurred during execution: Error while communicating with the Moodle System! (Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD")

```

**Comment by marcoscale98** [comment]
I think that it's not good for the user to see the exception. 
I manage the exception but I don't know how to make a pull request (I'm not very expert)

**Comment by C0D3D3V** [comment]
Or do you like this more:

```
moodle-dl                                                                                                                  SIGEXIT(127) ↵  daniel@DerGeraet   96% ▇ 
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account....
Downloading account information

The following error occurred during execution: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"
```


```
moodle-dl -v                                                                                                                 SIGEXIT(2) ↵  daniel@DerGeraet   96% ▇ 
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account....
Downloading account information

Exception:
Traceback (most recent call last):
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/main.py", line 227, in run_main
    changed_courses = moodle.fetch_state()
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/moodle_service.py", line 231, in fetch_state
    userid, version = first_contact_handler.fetch_userid_and_version()
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
    result = self.request_helper.post_REST('core_webservice_get_site_info')
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 126, in post_REST
    json_result = self._initial_parse(response)
  File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 262, in _initial_parse
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"

The following error occurred during execution: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"
```

**Comment by marcoscale98** [comment]
> Or do you like this more:
> 
> ```
> moodle-dl                                                                                                                  SIGEXIT(127) ↵  daniel@DerGeraet   96% ▇ 
> Moodle Downloader starting...
> Loading config...
> Checking for changes for the configured Moodle-Account....
> Downloading account information
> 
> The following error occurred during execution: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"
> ```
> 
> ```
> moodle-dl -v                                                                                                                 SIGEXIT(2) ↵  daniel@DerGeraet   96% ▇ 
> Moodle Downloader starting...
> Loading config...
> Checking for changes for the configured Moodle-Account....
> Downloading account information
> 
> Exception:
> Traceback (most recent call last):
>   File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/main.py", line 227, in run_main
>     changed_courses = moodle.fetch_state()
>   File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/moodle_service.py", line 231, in fetch_state
>     userid, version = first_contact_handler.fetch_userid_and_version()
>   File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
>     result = self.request_helper.post_REST('core_webservice_get_site_info')
>   File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 126, in post_REST
>     json_result = self._initial_parse(response)
>   File "/home/daniel/Desktop/other_repos/Moodle-Downloader/moodle_dl/moodle_connector/request_helper.py", line 262, in _initial_parse
>     raise RequestRejectedError(
> moodle_dl.moodle_connector.request_helper.RequestRejectedError: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"
> 
> The following error occurred during execution: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD"
> ```

The first

**Comment by C0D3D3V** [comment]
Ok it will be in the next release. Thanks for the idea :+1:
