### ISSUE TITLE
Moodle-dl stopped working

### ISSUE THREAD

**Issue by kinkamez** [C0D3D3V/Moodle-Downloader-2#69]
I am on **Manjaro** ,  _unstable_ branch.  After a distro  update moodle-dl stopped working, before that everything worked as should . 
_python2-importlib-metadata 2.1.1-1
python-importlib-metadata 3.1.1-1_ are installed and moodle-dl-git from AUR. 

```
Dec 10 12:02:41 kinka-pc moodle-dl[619]:   File "/usr/bin/moodle-dl", line 22, in importlib_load_entry_point
Dec 10 12:02:41 kinka-pc moodle-dl[619]:     for entry_point in distribution(dist_name).entry_points
Dec 10 12:02:41 kinka-pc moodle-dl[619]:   File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
Dec 10 12:02:41 kinka-pc moodle-dl[619]:     return Distribution.from_name(distribution_name)
Dec 10 12:02:41 kinka-pc moodle-dl[619]:   File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
Dec 10 12:02:41 kinka-pc moodle-dl[619]:     raise PackageNotFoundError(name)
Dec 10 12:02:41 kinka-pc moodle-dl[619]: importlib.metadata.PackageNotFoundError: moodle-dl
```

**Comment by C0D3D3V** [comment]
Yes I had a similar problem on Arch Linux. I don't know what exactly is going wrong. But I just uninstalled moodle-dl and dependencies that I had installed manually, and then reinstalled moodle-dl. After that, everything worked as normal. 

Sorry, I don't have time to look into what exactly changed, but reinstalling helped me.

**Comment by kinkamez** [comment]
Helped me to! Thank you.

**Comment by Krusty27** [comment]
Reinstalling doesn't work for me, do you have any other suggestion? Doing `yay -S moodle-dl-git` raises the error: `AttributeError: module 'collections' has no attribute 'Callable'
 ==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: python-aiosasl`

**Comment by C0D3D3V** [comment]
try `yay -Rcns moodle-dl-git`
then `yay -Sy moodle-dl-git`

**Comment by Krusty27** [comment]
This did not work, the first one saying that it moodle-dl-git couldn't be found (because I removed it) and the second one raising the attached error:
![image](https://user-images.githubusercontent.com/28927643/150704182-ffe63b68-b2c9-45e2-b0bf-58cea5a76683.png)
