### ISSUE TITLE
Can't obtain SSO token

### ISSUE THREAD

**Issue by jeremias-jordan** [C0D3D3V/Moodle-Downloader-2#80]
Hi there,

for some reason i can't obtain the SSO token of my institution manually. The moodle version of my institution is 3.94. 

None of the addresses in the developer options look like the given format (moodledownloader://token=$apptoken) and neither does it work with cookies from the site i copied manually.

The Institutions login method is shibboleth if this helps.

![Bildschirmfoto 2021-02-25 um 11 49 24](https://user-images.githubusercontent.com/75341282/109143170-02a70c80-7760-11eb-91e1-611a84343ed2.png)
![Bildschirmfoto 2021-02-25 um 11 53 36](https://user-images.githubusercontent.com/75341282/109143377-413cc700-7760-11eb-8c11-361db14a7d28.png)

Here's the Terminal output in case it helps:

```
Please log into Moodle on this computer and then visit the following address in your web browser: 
https://moodle.tum.de/admin/tool/mobile/launch.php?service=moodle_mobile_app&passport=12345&urlscheme=moodledownloader
If you open the link in the browser, no web page should load, instead an error will occur. Open the developer console (press F12) and go to the Network Tab, if there is no error, reload the web page.
Copy the link address of the website that could not be loaded (right click, then click on Copy, then click on copy link address).
The script expects a URL that looks something like this:`moodledownloader://token=$apptoken`. Where $apptoken looks random. In reality it is a Base64 encoded hash and the token we need to access moodle.
Then insert the address here:   moodledownloader://token=oa5cm5dtj6ggm70*********
Traceback (most recent call last):
  File "/usr/local/bin/moodle-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/moodle_dl/main.py", line 559, in main
    run_init(storage_path, use_sso, skip_cert_verify)
  File "/usr/local/lib/python3.9/site-packages/moodle_dl/main.py", line 75, in run_init
    moodle.interactively_acquire_sso_token()
  File "/usr/local/lib/python3.9/site-packages/moodle_dl/moodle_connector/moodle_service.py", line 188, in interactively_acquire_sso_token
    moodle_token, moodle_privatetoken = sso_token_receiver.extract_token(token_address)
  File "/usr/local/lib/python3.9/site-packages/moodle_dl/moodle_connector/sso_token_receiver.py", line 45, in extract_token
    decoded = str(base64.b64decode(splitted[1]))
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

Kind regards

**Comment by C0D3D3V** [comment]
The `MoodleSession` Cookie can not be used for moodle-dl. Moodle-dl itself can generate a cookie, but it needs the private-token and api-token to work.

Did you try to connect the Moodle-App (Android or IOS) to your moodle platform?  Its a good indicator that if you can connect with the app, that you can use moodle-dl. If you can not connect with the moodle app there is only little hope that you can use moodle-dl.


Can you also send a picture of the webpage (that you opend to get the token), if the webpage tells you that the plugin is not activated then there is nothig I can do. But you could als the maintainers to activate the moodle app for your moodle platform.

**Comment by jeremias-jordan** [comment]
Thanks for your quick reply!

I tried logging in with the Moodle-App, but it seems that web services aren't activated so then i guess there is no chance. 
Also i screenshotted the webpage and i guess it also means that the plugin isn't activated. 

Anyways, i appreciate the time for your reply and coding this tool.

![Bildschirmfoto 2021-02-25 um 21 21 13](https://user-images.githubusercontent.com/75341282/109212215-889e7400-77af-11eb-93ce-bb38f52d8804.png)

**Comment by C0D3D3V** [comment]
Em, the error indicates that the parameter "service" is missing. Did you realy use the correct link?

**Comment by jeremias-jordan** [comment]
Yes i used this link. In case you want to double check, i attached the screen record:

https://user-images.githubusercontent.com/75341282/109232106-08d0d380-77c8-11eb-917b-284c934249cf.mov

**Comment by C0D3D3V** [comment]
I tried it myself with this [link](https://www.moodle.tum.de/admin/tool/mobile/launch.php?service=moodle_mobile_app&passport=12345&urlscheme=moodledownloader).
But then you get the error message I meant (maybe it was your browser not passing the parameters correctly).
![Screenshot_20210226_084058](https://user-images.githubusercontent.com/14315968/109270566-7dc6fc00-780e-11eb-8223-26b5e7a3b152.png)

Maybe there is another way to get the tokens from shibboleth. Unfortunately I don't know another way, but maybe you can find out something.

**Comment by jeremias-jordan** [comment]
I tried it again and i got the same page as you. I noticed that the only difference was the "www." subdomain in the URL. 
Unfortunately i still don't get the right token. Is this error message supposed to be an indicator that i should be able to get the right token now?
I also did a little bit of research but so far i didn't find a workaround for this issue.

![Bildschirmfoto 2021-02-26 um 22 26 31](https://user-images.githubusercontent.com/75341282/109357344-5ad62f80-7882-11eb-8ab0-1283c43e09d3.png)

**Comment by C0D3D3V** [comment]
Well done :)
No, I'm sorry, the error message is an indicator that you are not able to generate a token.

**Comment by C0D3D3V** [comment]
But you could ask the Moodle admins if they could take care of activating the Moodle app for you students. The TUM actually has enough money to activate the Moodle app. I don't understand why the universities save on this point. Well, digitalization is a foreign word in Germany. -.- So sad

**Comment by jeremias-jordan** [comment]
Yes, you're right.. I guess in theory it should be easily possible to activate this function. What a shame.. Well, let's see if I can convince the adminis.
Anyway thank you for your help again. I appreciate it.
