### ISSUE TITLE
Support for Data images

### ISSUE THREAD

**Issue by jopejoe1** [C0D3D3V/Moodle-Downloader-2#81]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

Not saving data images and brings up an error of to long file name
## Describe the solution you'd like

encode data images to image file
## Additional context

Logs
[https://pastebin.com/4Qmv08Vi](https://pastebin.com/4Qmv08Vi)
[https://pastebin.com/MSjUXT7s](https://pastebin.com/MSjUXT7s)
[https://pastebin.com/4VYc9yDk](https://pastebin.com/4VYc9yDk)

**Comment by C0D3D3V** [comment]
Thanks for the report :)

You are welcome to do a Pull Request, if you don't want to, I can fix it in the next few day.

**Comment by C0D3D3V** [comment]
Does that work now too?

**Comment by jopejoe1** [comment]
Partly it saves the data image URL, but it just turns it into a .desktop file and not into an image file.

**Comment by C0D3D3V** [comment]
I hope [this](https://github.com/C0D3D3V/Moodle-Downloader-2/commit/284f84614934d6d9ca279ffdec0884d1d0cdb873) fiexed it.
If you have time, it would be great if you test it.

**Comment by jopejoe1** [comment]
Nope getting 2 different errors this time.

One of the images gets this error message:
`Invalid base64-encoded string: number of data characters (297869) cannot be 1 more than a multiple of 4`

and the other image gets turn into an image file but is still named .desktop at the end.

**Comment by C0D3D3V** [comment]
By the way :D your pastbin's are private, except one. 

Could you test the latest commit? In my test it worked.

**Comment by jopejoe1** [comment]
Yeah, works fine now,

For some reason pastebin decided that my logs are `potentially offensive or questionable content`

**Comment by C0D3D3V** [comment]
xD ok interesting. I will publish it right away.
