### ISSUE TITLE
Failed to download forum

### ISSUE THREAD

**Issue by jopejoe1** [C0D3D3V/Moodle-Downloader-2#82]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

 If download forum is set to true i get an error message

## Steps to reproduce the issue
start moodle-dl with forums enabled

Log
[https://pastebin.com/EWQ76jKH](https://pastebin.com/EWQ76jKH)
 

## Expected behavior

Not crashing

## Possible Fix
looks like a forum was empty this could probably be the issue

**Comment by C0D3D3V** [comment]
Interessting, thanks for reporting :)
Will be fixed tomorrow...

**Comment by C0D3D3V** [comment]
Can you test moodle-dl manually with the latest commit and check if the two errors still occur? If not, I can also release first, then you can update normally.

**Comment by jopejoe1** [comment]
Okay, that fixed it works fine now.
