### ISSUE TITLE
Pressing Enter is not recognized as Confirm

### ISSUE THREAD

**Issue by AlexBocken** [C0D3D3V/Moodle-Downloader-2#83]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

Pressing `Enter` is not registered as confirm for the Yes/No questions. I had to manually change  `cutie.py` to also confirm with `Ctrl+R`. Then everything worked as it should.

## Steps to reproduce the issue

You can see here what happens after multiple enter key presses:
<img src="https://bocken.org/Enter_moodledl.png">
 `Enter` just gets treated as a normal input.

I'm running zsh as my shell but the issue als persists in bash. (just in case it's because of the shell?)

This is the class I modified as you can see below:

`utils/cutie.py`:
```python
class DefaultKeys:
    """List of default keybindings.
    Attributes:
        interrupt(List[str]): Keys that cause a keyboard interrupt.
        select(List[str]): Keys that trigger list element selection.
        confirm(List[str]): Keys that trigger list confirmation.
        delete(List[str]): Keys that trigger character deletion.
        down(List[str]): Keys that select the element below.
        up(List[str]): Keys that select the element above.
    """

    interrupt: List[str] = [readchar.key.CTRL_C, readchar.key.CTRL_D]
    select: List[str] = [readchar.key.SPACE]
    confirm: List[str] = [readchar.key.ENTER, readchar.key.CTRL_R] #modified this line
    delete: List[str] = [readchar.key.BACKSPACE]
    down: List[str] = [readchar.key.DOWN, 'j']
    up: List[str] = [readchar.key.UP, 'k']
    tab: List[str] = ['\t']
```

## Technical details

OS: Arch Linux 
Kernel: 5.11.2-arch1-1
Python: 3.9.2
Version: Most recent commit (https://github.com/C0D3D3V/Moodle-Downloader-2/commit/284f84614934d6d9ca279ffdec0884d1d0cdb873). Building an older commit (https://github.com/C0D3D3V/Moodle-Downloader-2/commit/21f580a165775f8e270cb0743b358c0f6185734e) did not solve the issue for me. 

A friend of mine tried to use it on MacOS and experienced the same issue as I did.

## Expected behavior

treat `Enter` as confirm.

## Possible Fix

Did the syntax for the Enter key recently change? Maybe that's a reason. No idea.

**Comment by C0D3D3V** [comment]
I think the problem is maybe that aur/python-readchar got an update from ~ 2.0.0-1-> 3.0.3-1

I will test it

**Comment by C0D3D3V** [comment]
I asked @magmax to undo the change. Let's wait :)

**Comment by AlexBocken** [comment]
Awesome, thanks for the quick work from your side!

**Comment by C0D3D3V** [comment]
I fixed it in our project, so we don't have to wait :)
