### ISSUE TITLE
Change in filename_tmpl when downloading youtube video

### ISSUE THREAD

**Issue by yuki** [C0D3D3V/Moodle-Downloader-2#95]
In https://github.com/C0D3D3V/Moodle-Downloader-2/blob/9bb60aee79e467cce35ccb150b45454475c583df/moodle_dl/download_service/url_target.py#L430 the filename_tmpl of the video adds a "|" which is not permited in Windows.

I have used Moodle-downloader on Linux but when trying to move files to a windows machine the videos can't be moved because of the name.

It would be great to have an option to change the "filename_tmpl" in a config parameter or change the "|" with a "-", for example.

Thanks.

**Comment by C0D3D3V** [comment]
that is indeed a good idea, thank you very much.
 I should now have more free time for my own projects, so I can fix this tomorrow :)
